using Pipelink.Interfaces;

namespace Pipelink.Behaviors;

/// <summary>
/// Represents a logging behavior in a pipeline that allows capturing and logging
/// information during the handling of a request.
/// </summary>
/// <typeparam name="TRequest">The type of the request being handled. Must implement <see cref="IRequest{TResponse}"/>.</typeparam>
/// <typeparam name="TResponse">The type of the response returned by the handler.</typeparam>
/// <remarks>
/// This behavior logs the handling start and completion of the request, facilitating tracing and debugging.
/// </remarks>
public class LoggingBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
{
    /// <summary>
    /// Handles the processing of a request through the pipeline. This method logs the start and end of the handling process.
    /// </summary>
    /// <param name="request">The request object being processed.</param>
    /// <param name="cancellationToken">A token to cancel the processing operation.</param>
    /// <param name="next">The delegate invoking the next handler in the pipeline.</param>
    /// <returns>The response of type <typeparamref name="TResponse"/> generated by processing the request.</returns>
    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        Console.WriteLine($"[LOG] Handling {typeof(TRequest).Name}");
        var response = await next();
        Console.WriteLine($"[LOG] Handled {typeof(TRequest).Name}");
        return response;
    }
}
